name: Auto Fork Branch

on:
  push:
    branches:
      - "17.0" # Replace source-branch with the branch you want to monitor for changes

jobs:
  fork_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Fork repository
        uses: peter-evans/create-pull-request@v3
        with:
          branch: 17.0 # Replace 17.0 with the branch you want to fork
          title: "Auto fork branch 17.0"
          body: "Automatically forked 17.0 branch from upstream repository"
          base: main # Replace main with the branch you want to fork into

         
   
                
      
    
